- name: Configuration NAT
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
    - name: NAT
      cisco.ios.ios_config:
        lines:
          - no access-list 1
          - access-list 1 permit 192.168.2.0 0.0.0.255
          - access-list 1 permit 192.168.3.0 0.0.0.255
          - access-list 1 permit 192.168.4.0 0.0.0.255
          - ip nat inside source list 1 Interface g1 overload

    - name: Nat Sortant
      cisco.ios.ios_config:
        lines:
          - ip nat outside
        parents: Interface g1

    - name: Nat Entrant
      loop:
        - g2
        - g3
        - g4
      cisco.ios.ios_config:
        lines:
          - ip nat inside
        parents: interface {{item}}

    - name: Nat Statique
      cisco.ios.ios_config:
        lines:
          - ip nat inside source static tcp 192.168.3.2 80 interface g1 80
          - ip nat inside source static tcp 192.168.4.2 22 interface g1 2222

    - name: Enregistrement Configuration 
      cisco.ios.ios_config:
        save_when: modified
