- name: Configuration Interface
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
    - name: Configuration Int GIGA
      # On indique le nom du module
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: Interface G1 Configuré par Ansible Network
            enabled: true
          - name: GigabitEthernet2
            description: Interface G2 Configuré par Ansible Network
            enabled: true
          - name: GigabitEthernet3
            description: Interface G3 Configuré par Ansible Network
            enabled: true
          - name: GigabitEthernet4
            description: Interface G4 Configuré par Ansible Network
            enabled: true
        state: merged

    - name: Configuration IP Int GIGA
      # On indique le nom du module
      cisco.ios.ios_l3_interfaces:
        config:
          - ipv4:
            - dhcp:
                enable: true
            name: GigabitEthernet1
          - ipv4:
              - address: 192.168.2.1/24
            name: GigabitEthernet2
          - ipv4:
              - address: 192.168.3.1/24
            name: GigabitEthernet3
          - ipv4:
              - address: 192.168.4.1/24
            name: GigabitEthernet4
        state: merged
    - name: Suppression DHCP
      cisco.ios.ios_config:
        lines:
          - no ip dhcp pool Server
          # On retire le pool dhcp "Server" si il y en a un pour éviter les problèmes de pool déjà existant
    - name: Mise en place DHCP
      cisco.ios.ios_config:
        lines:
          - ip dhcp pool Server
          #Création du pool DHCP
          - network 192.168.2.0 255.255.255.0
          #Ajout du réseau et mask réseau
          - default-router 192.168.2.1
          #Ajout de la passerelle par défaut
          - dns-server 8.8.8.8
          #Ajout d'un server DNS