- name: Acte II - Configuration Serveur Web
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: web
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false
  become : yes

  # Liste des tâches associées à notre Acte
  tasks:
    - name: apt upgrade
      ansible.builtin.apt:
        update_cache: yes

    - name: apt install
      ansible.builtin.apt:
        name: apache2
        state: latest

    - name: copie fichier
      ansible.builtin.copy:
        src: /home/utilisateur/td_ansible_infra/ConfigAnsible/files/site_web/index.html
        dest: /var/www/html/index.html
        owner: www-data
        mode: 0600

    - name: redémarrage apache
      ansible.builtin.systemd_service:
        name: apache2
        state: restarted
        enabled: yes